name: .NET
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          check-latest: true
          
    #  - name: Set up .NET
    #    run: >
    #      $url =
    #      'https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.200-windows-x64-installer'
    #      $fileName = 'dotnet-sdk-6.0.200-win-x64.exe'
    #      Invoke-WebRequest -Uri $url -OutFile $fileName
    #      .\$fileName /quiet
    #      # Set DOTNET_ROOT environment variable
    #      echo "DOTNET_ROOT=C:\Program Files\dotnet" >> $Env:GITHUB_ENV
    #  - name: Setup MSBuild
    #    uses: microsoft/setup-msbuild@v1
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build and Publish package
        run: |
          dotnet build
          dotnet publish -c Release -r win-x64 -o ../publish B1Test.sln;

      #- name: Restore Packages
      #  run: nuget restore B1Test.sln
      #- name: Build solution
      #  run: 'msbuild B1Test.sln -t:rebuild -property:Configuration=Release'

#- name: Set up .NET
#        run: >
#          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin
#          --install-dir $HOME/.dotnet --channel 6.0
#          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

# dotnet build --configuration Release --no-restore
