name: .NET
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      #- name: Setup MSBuild1
      #  uses: microsoft/setup-msbuild@v1.1
      - name: Setup .Net
        uses: action/setup-dotnet@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Restore Packages
        run: nuget restore B1Test.sln
      - name: Build solution
        run: 'msbuild B1Test.sln -t:rebuild -property:Configuration=Release'
