name: .NET
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          check-latest: true
      - name: Set up .NET
        run: >
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin
          --install-dir $HOME/.dotnet --channel 6.0

          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build and Publish package
        run: >
          cd B1Test

          dotnet build --configuration Release --no-restore

          dotnet publish --configuration "Release" --self-contained "true" -o
          ../publish;

      #- name: Restore Packages
      #  run: nuget restore B1Test.sln
      #- name: Build solution
      #  run: 'msbuild B1Test.sln -t:rebuild -property:Configuration=Release'
